### ISSUE TITLE
Incompatible Datapack(s)

### ISSUE THREAD

**Issue by Coraline77447** [Sinhika/Fusion#11]
Hi. I'm here to report an issue involving datapacks with this mod and why I'm reporting this about it's datapack(s) is cause I'm sick and tired of losing my worlds due to incomplete or missing data within the datapacks or outdated datapacks of some of the mods that I'm playing with which at some point I lose the world that I would be playing on and how I know this is cause when making a new world you can apply datapacks except for datapacks that mods adds, when I look in there I see some red ones that when I hover my mouse over them they say "Incompatible, made for an older version of Minecraft." When I would try to load into a modded world I get a message that says that the selected datapacks have errors and asks me to either enter safe mode (which I can't enter safe mode) or go to title screen and in the message it says that I can manually fix them which Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors!!!

**Comment by Sinhika** [comment]
I do not understand your problem. You're obviously frustrated, but I don't maintain modpacks. I only work on the SimpleOres mod and its related add-ons, such as Fusion that I have taken over maintenance for. If one of my mods is giving you an outdated/incompatible datapack version, could you tell me which mod and which version, and the usual which Minecraft version and Forge version you are running it under? I do not see a datapack issue when running the correct version of Fusion under 1.16.4, if that is what you are reporting.

**Comment by Coraline77447** [comment]
I'm running on Minecraft 1.16.4, Forge 1.16.4, Forge version 35.0.1, and Fusion 2.7.1.0. 

How I've discovered this issue is when I was making a new world (cause the last world I had was un-joinable due to selected datapacks that have errors that prevented the world from loading) and in the datapacks option menu I saw that Fusion has incompatible datapack(s) that are "made for an older version of minecraft" which I don't know why my game was telling me that when you're not experiencing this issue. Anyways I'm not playing with Fusion cause of this issue and Im not playing with Simple Ores cause I'm playing with a gun mod called A.V.A  I've uninstalled all of the mods that I was playing with that adds weapons and their respective ores cause I would've had too many weapons to choose from, I'm fine with the vanilla weapons aka swords (I mainly like to use axes even tho they're slower than swords but idc) that I can use as close combat weapons while using A.V.A's firearms for long range shooting at my enemies (I know that all of what I've said from "Anyways" to "enemies" isn't important or relevant but why cant I tell ya what I have planned for my next modded adventure? Just asking btw)

**Comment by Sinhika** [comment]
May I ask how you are doing that? The only version of SimpleCoreLib for 1.16.4  requires Forge 1.16.4-35.0.**7** or later to run.

Also, this may be a silly question, but did you get your mods from CurseForge or some other source? The reason I ask this is that there are quite a few bad sites on the web such as 9minecraft that re-post mods without asking and mislabel them as being for later versions than they actually are.

**Comment by Coraline77447** [comment]
I always download mods from curseforge and rarely from planet minecraft but mainly from curseforge cause it's the most safest way to get mods and I was able to play with Fusion for forge version 35.0.17, 35.0.18 and 35.1.0 wont do so till Fusion's datapack gets updated to version 6 cause apparently it's at version 5 and I don't know why that minecraft's datapack system is telling me that Fusion's datapack is outdated when this mod doesn't add any worldgen content at all. All that Fusion adds is a furnace like block that fuses metals to make other metals like bronze or steel for an example. Right? (Btw I've edited this cause when you said what version of SimpleCoreLib I'm using but I thought that you said "what version of Fusion are you using?" And why I'd edited it to say 35.0.17, 35.0.18, and 35.1.0 is cause I remember before I've made my current modded world that I'm playing on I had minecraft and forge loaded at forge version 35.1.0 with SimpeCoreLib in my mods folder before I uninstalled it cause of A.V.A mod (it's a modern minecraft gun mod which is kind of like a well known gun mod for 1.12.2 called Vic's Modern Warfare mod but sadly Vic and his Contagion team arnt porting their mod to modern minecraft versions cause of how the devs od forge changed the rendering system entirely to the point that Vic's Modern Warfare 2.0 Contagion will no longer work since that mod is heavily dependent on the old forge rendering system and they've spent literally 4 years on that mod cause if they were to try to port it to newer versions of minecraft they would've had to rebuild the mod from the ground up and they don't want to do that cause all of that hard determination and work for the last  4 or so years would've went down the drain so I'm glad that A.V.A exists but the owner of that mod wont make the mod to be like V.M.W. 2.0 Contagion mod... (sorry for this sentence that's not about this mod and the issue, gotten too carried away with what I was saying that was coming from my thoughts...)

**Comment by Sinhika** [comment]
Try re-downloading Fusion for 1.16.4. It sounds like you somehow got an old version.
~~The current version is here:  https://www.curseforge.com/minecraft/mc-mods/fusion/files/3107313~~

**Comment by Sinhika** [comment]
Okay, you were correct, Fusion's resource pack was still listing itself as version 5 when it should have been upgraded to version 6 about 2 Minecraft patches ago. I don't understand why my Minecraft client was not complaining about the out-of-date resource pack, though.

I will be posting an update to CurseForge shortly. New version, disregard the above comment.

**Comment by Coraline77447** [comment]
Alright, btw before you did that I went into the mods meta folder and updated it's pack_format to 6 and when I look in the datapack options its not red anymore and I've done that to almost all 25 mods that has this issue but 10 or so mods I can't do that cause in the file where the pack_format is at that there's a line called _comment that says what pack version for all mods that the owner made to work on the version the owner of the mod has it set to and if I were to change it then I could've caused something bad to the mod or worse so I left those mods pack_format alone only for the owners of those mods to do the change it themselves. An example of one of those mods that I can't change it's pack_format is Artifacts mod.
