### ISSUE TITLE
bug with bows

### ISSUE THREAD

**Issue by Celophy** [Sinhika/Fusion#13]
with last release and 1.16.5 the bows of the mod does the same damage ad the vanilla bow

**Comment by Sinhika** [comment]
I need more information, please.

What did you expect the Thyrium and Sinisite bows to do? What did they actually do?

**Comment by Sinhika** [comment]
Okay, nevermind, I see the problem. I completely forgot to implement the bow special properties. I'll have it fixed next release.

**Comment by Sinhika** [comment]
FIxed as of release 1.16.5-2.7.3.2.
