### ISSUE TITLE
Server environment, when using the fusion furnace, the client crashes

### ISSUE THREAD

**Issue by Acerie** [Sinhika/Fusion#15]
As the title says, error report is here.
[crash-2021-09-02_14.21.46-client.txt](https://github.com/Sinhika/Fusion/files/7096632/crash-2021-09-02_14.21.46-client.txt)

**Comment by wanitou** [comment]
same issue

**Comment by Sinhika** [comment]
Should be fixed by new version [Fusion-1.16.5-2.7.4.5.jar](https://www.curseforge.com/minecraft/mc-mods/fusion/files/3692685) I just uploaded. Please test; it worked fine in my test client/dedicated server environment.
