### ISSUE TITLE
1.19.2 client crash with Fusion furnace

### ISSUE THREAD

**Issue by Zygus42** [Sinhika/Fusion#17]
SimpleOres2-1.19.2-5.1.0.0
SimpleCoreLib-1.19.2-5.1.0.2
SimpleOres2-Fusion-1.19.2-5.1.0.0
SimpleOres2-Netherrocks-1.19.2-5.1.0.2

Placed fusion furnace, input stack of redstone  in top slot.  Client crashed, but not server - even crashed the minecraft launcher, which i've never seen before.

This does not happen if only the above mods are on and you're in singlepayer, but does happen if only these mods are installed and you're on a server that also only has these mods installed.

client:
[crash-2022-09-29_13.
[latest.log](https://github.com/Sinhika/Fusion/files/9671155/latest.log)
[debug.log](https://github.com/Sinhika/Fusion/files/9671156/debug.log)

server:
[latest.log](https://github.com/Sinhika/Fusion/files/9671146/latest.log)
[debug.log](https://github.com/Sinhika/Fusion/files/9671147/debug.log)

**Comment by Sinhika** [comment]
Oops. Thanks for catching that one--I was crossing the streams.

Fixed with Fusion-1.19.2-5.1.1.0.  Backported fixes for earlier versions TBD.
