### ISSUE TITLE
Fusion furnace bugs

### ISSUE THREAD

**Issue by fearheaven** [Sinhika/Fusion#4]
In the latest Fusion version (fusion-1.12.2-2.4.1.4), I spotted 3 bugs in both single and multi-player with the fusion furnace :

1 : The fusion furnace stays lit after all fuel has been used and the furnace isn't working anymore.
Only tested with coal as fuel.
No fix found.

2 : Every time a an alloy chunk is finished, it consumes 2 catalyst and 2 of each ingredients used for the fusion instead of 1. Basically making fusion twice as expensive, the fuel is still consumed as it should.
Tested with large bronze and steel chunks, as well as all thyrium chunk size.
Note : If there is only one catalyst or ingredient left, the fusion will work and the chunk will be created, so you can place the catalyst and ingredients one by one to have normal resources usage.

3 : The fusion furnace isn't lootable. When it is broken with a pickaxe (tested with iron and steel pickaxe), it is destroyed and drops some xp.

Also, on mutli-player, this line is repeated on the server's (1 to sometimes 6 times in 1-2 seconds) every few minutes : 
"[Server thread/INFO] [fusion]: finished TileEntityFusionFurnace ctor for Fusion Furnace"

**Comment by Sinhika** [comment]
Fixed with commit #6c38b88645f4fa38199c6973fc5a71037028f614.
